replicaCount: 1

image:
  repository: hello-world
  pullPolicy: IfNotPresent
  tag: "1"

service:
  type: NodePort
  port: 5000  # Port to expose
  targetPort: 5000 # this value is the same for both the service TargetPort and the deployments ContainerPort

resources: {}

